@startuml
[*] -> inventory
inventory -> [*] : exit
inventory --> order_settings_popup : order
inventory --> location : sort_menu
inventory --> forecast : forecase_menu
inventory --> shipping_screen : ?
inventory --> set_reorder_point : ?
@enduml
